# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Woke < Formula
  desc "Detect non-inclusive language in your source code."
  homepage "https://getwoke.tech"
  version "0.10.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/get-woke/woke/releases/download/v0.10.0/woke-0.10.0-darwin-amd64.tar.gz"
      sha256 "9d58fa4b8afbef28645eb79924ffcbaa540c8f25add791bb96d70eee896ecf4c"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/get-woke/woke/releases/download/v0.10.0/woke-0.10.0-linux-amd64.tar.gz"
      sha256 "48152a0f08886453cc49adcc21f29a05cfc15dd5d0ce8b35dbdf2f75991634e0"
    end
  end

  def install
    bin.install "woke"
  end

  test do
    system "#{bin}/woke --version"
  end
end
