# This file was generated by GoReleaser. DO NOT EDIT.
class Woke < Formula
  desc "Detect non-inclusive language in your source code."
  homepage "https://getwoke.tech"
  version "0.4.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/get-woke/woke/releases/download/v0.4.0/woke-0.4.0-darwin-amd64.tar.gz"
    sha256 "972c47654c2bafd4edb3f703af61874aa7b8281a7889eda17e4dec6686414cad"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/get-woke/woke/releases/download/v0.4.0/woke-0.4.0-linux-amd64.tar.gz"
      sha256 "5d17797814c15148c8b13d1d03a16b626ffff7e4a560109e411658ae80c1a2c3"
    end
  end

  def install
    bin.install "woke"
  end

  test do
    system "#{bin}/woke --version"
  end
end
